spring:
  application:
    name: paofresquim
  datasource:
    url: jdbc:sqlite:C:\Users\koi\Projeto_Sistemas\Pao-FresQUIM\backend\paofresquim\src\main\resources\database\paofresquim.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.generate_statistics]": false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    "[com.paofresquim]": INFO
    "[com.paofresquim.controller]": INFO
    "[com.paofresquim.service]": INFO
    "[com.paofresquim.repository]": DEBUG
    
    "[org.springframework.web]": INFO
    "[org.springframework.transaction]": INFO
    "[org.springframework.orm.jpa]": INFO
    
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": INFO
    "[org.hibernate.stat]": INFO
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId:-no-trace}] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{40} - [%X{traceId:-no-trace}] %msg%n"
  
  file:
    name: logs/paofresquim.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 100MB

server:
  port: 8080