spring:
  application:
    name: paofresquim
  datasource:
    url: jdbc:sqlite:${user.dir}/backend/paofresquim/src/main/resources/database/paofresquim.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create  # update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.generate_statistics]": false
  sql:
    init:
      mode: never

logging:
  level:
    "[com.paofresquim]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.springframework.jdbc.core]": TRACE

server:
  port: 8080